### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by wuduxunran** [autonlab/auton-survival#135]
Dear：

I am installing the package, however, get the following error:

ERROR: Ignored the following versions that require a different python version: 0.27.3 Requires-Python >=3.7, !=3.11.*
ERROR: Could not find a version that satisfies the requirement torch<2.0,>=1.13 (from auton-survival) (from versions: 2.0.0, 2.0.1, 2.1.0)
ERROR: No matching distribution found for torch<2.0,>=1.13

Is this package not suitable for python3.11 and torch2.0? If not, is there a suitable version for python3.11 and torch2.0?

**Comment by matteo4diani** [comment]
Hi @wuduxunran, thanks for reaching out 🙂 we're working on this issue #136, as you can see allowing torch v2 creates some problems in <3.11 builds: I need to understand how to handle this with poetry.

In the meantime, if you want to try using auton-survival with torch 2, you can use the following pyproject.toml (or install with pip as a VCS dependency):

```toml
[tool.poetry]
name = "your-package"
version = "0.1.0"
description = ""
authors = ["Name Surname <name.surname@example.com>"]
readme = "README.md"
packages = [{include = "your_package"}]

[tool.poetry.dependencies]
python = "~3.11"
auton-survival = {git = "https://github.com/matteo4diani/auton-survival.git", rev = "dev-mfordiani-135-torch-2"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
